name: Deploy to Google Cloud Run

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      # Debug step to see GitHub token claims
      - name: Debug OIDC Claims
        run: |
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=https://iam.googleapis.com" | jq .

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}
          create_credentials_file: true
          token_format: "access_token"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push Backend
        run: |
          docker build -t gcr.io/$PROJECT_ID/urlshortener-backend .
          docker push gcr.io/$PROJECT_ID/urlshortener-backend

      - name: Build and Push Frontend
        run: |
          docker build -t gcr.io/$PROJECT_ID/urlshortener-frontend ./web
          docker push gcr.io/$PROJECT_ID/urlshortener-frontend

      - name: Deploy Backend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: urlshortener-backend
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/urlshortener-backend
          env_vars: |
            REDIS_ADDR=${{ secrets.REDIS_ADDR }}
            REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}
            REDIS_DB=0
            SERVER_PORT=8080
            BASE_URL=${{ secrets.BACKEND_URL }}

      - name: Deploy Frontend to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: urlshortener-frontend
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/urlshortener-frontend
          env_vars: |
            VITE_API_BASE_URL=${{ secrets.BACKEND_URL }}
